version: '3.9'

services:
  streamlit:
    container_name: streamlit-dev
    build:
      context: .
      target: dev
    image: tzelleke/streamlit-dev
    ports:
      - "127.0.0.1:${PORT:-8501}:8501"
    volumes:
      - ./config:/root/.streamlit
      - ./:/streamlit
